server:
  port: 8085

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce?createDatabaseIfNotExist=true
    username: admin01
    password: H1f78tnajhg&*
    hikari:
      auto-commit: true
      minimum-idle: 1
      maximum-pool-size: 10
      idle-timeout: 600000
      pool-name: SpringBootJPAHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/ecommerce-realm


keycloak:
  admin-cli:
    realm: master
    client-id: admin-cli
    username: admin
    password: admin
  auth-server-url: http://localhost:8080
  realm: ecommerce-realm
  client-id: ecommerce
  client-secret: 4lFakjslcj1I2hRY2RTcVixhlRZCyAAw


logging:
  level:
    org.keycloak: DEBUG
    org.springframework.security: DEBUG

